name: Create deployment when PR opened
on:
  pull_request:
    types:
      - opened
      
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz
        
      - name: Create Deployment
        run: |
          # command line needs to be able to accept the url format in github.event.pull_request.url, but I will transform it here
          export gh_url = `echo ${{github.event.pull_request.url}} | sed -e 's/^https\:\/\/api\./https\:\/\//' | sed -e 's/github.com\/repos/github.com/'`
          
          ./salto-cloud deployment create from-pull-request -E f3b38076-6b87-4cf7-85aa-5ec14b8eb3a1 -u $gh_url
        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
