name: Create deployment when PR opened
on:
  pull_request:
    types:
      - opened
      
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Cache deployment ID
        uses: actions/cache@v3
        with:
          key: gwr
          path: |
            ~/salto
      - name: Test Cache
        run: |
          echo 1 ${{ github.ref }}
          echo 2 ${{ github.head_ref }}
          echo 3 ${{ github.event.ref }}
          echo 4 ${{ github.event.description }}
          echo 5 ${{ github.event.repository }}
          echo 6 ${{ github.action_ref }}
          cat ${{ github.event_path	}}
          ls ~ 
          mkdir ~/salto
          touch ~/salto/gwr20230914-010041
        
