name: test actions
on:
  workflow_dispatch:
  
      
jobs:
  GWR_test:
    runs-on: ubuntu-latest
    steps:
      - name: gwr_junk
        run: |
          # gh variable set GWR_TEST --body "Hello"
          gh pr list
        env:
          GH_REPO = workinman/netsuite_master
          GITHUB_TOKEN: ${{ secrets.GWR_GH_TOKEN }}
