name: Create Cache
on:
  create:
    branches:
      - main

jobs:
  create_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: 
          path: |
            ~/salto
    run: |
      touch ~/salto/${{github.event.ref}}

  
