name: Deploy to dev after merge
on:
  pull_request:
    types:
      - closed

jobs:
  Run-Salto-Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout repo
        uses: actions/checkout@v3
       

      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz

      - name: Run Deploy
        run: |

          # This file was created during the preceding workflow when the Salto deployment was created
          # here we are loading the deployment ID from a file that is cached and available for the merge workflow
          # NB: in the context of this workflow, github.ref contains the right name. 
          #     in the context of the pull_request, github.head_ref will contain that same information
          varname=$(echo ${{github.ref}}|sed -e 's/\-/_/g')
          varname=SALTO_${varname}
          
          
          echo $varname
          echo $depl_id
          
          ./salto-cloud deployment deploy -E ${{vars.SALTO_DEV_ENV}} -i $depl_id

        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
