name: Deploy to dev after merge
on:
  pull_request:
    types:
      - closed

jobs:
  Run-Salto-Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout repo
        uses: actions/checkout@v3
       

      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz

      - name: Run Deploy
        run: |

          # This variable was created during the preceding workflow when the Salto deployment was created
          # NB: in the context of this workflow, github.ref contains the right name. 
          #     in the context of the pull_request, github.head_ref will contain that same information
          cat <<EOF >tmpfile
          ${{vars.SALTO_DEPL_ID}}
          EOF

          #debug
          echo 1
          grep "${{github.event.pull_request.head.ref}}" tmpfile
          echo 2
          grep "${{github.event.pull_request.head.ref}}" tmpfile | sed -e 's/^${{github.event.pull_request.head.ref}}\://'
          echo 3

          depl_id=$(grep "${{github.event.pull_request.head.ref}}" tmpfile | sed -e 's/^${{github.event.pull_request.head.ref}}\://')
          
          # debug
          echo "__ $depl_id __"
          
          ./salto-cloud deployment deploy -E ${{vars.SALTO_DEV_ENV}} -i $depl_id

          # I could clean up vars.SALTO_DEPL_ID here with "grep -v" and "gh variable set"

        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
