name: Create deployment when PR opened
on:
  pull_request:
    types:
      - opened
      
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz
        
      - name: Create Deployment
        run: |

          # Salto command line should to be able to accept the url format in github.event.pull_request.url, 
          # but I will transform it here until that feature is created
          pr_url=$(echo ${{github.event.pull_request.url}} | 
             sed -e 's/^https\:\/\/api\./https\:\/\//' | 
             sed -e 's/github.com\/repos/github.com/' |
             sed -e 's/\/pulls\//\/pull\//' ) 
             
          ./salto-cloud deployment create from-pull-request -E ${{vars.SALTO_DEV_ENV}} -u $pr_url  |
             grep "https://app.salto.io" | 
             sed -e 's/^https\:\/\/.*\/deployments\///' > ~/deployment_id.txt

          # here we are saving the deployment ID into a variable that is available for the next workflow to inspect
          # NB: in the context of this workflow, github.head_ref contains the right name. 
          #     in the context of the merge, github.ref will contain that same information
          pr_id=$(echo ${{github.head_ref}}|sed -e 's/\-/_/g')
          depl_id=$(cat ~/deployment_id.txt)
          body="$pr_id:$depl_id
${{vars.SALTO_DEPL_ID}}"

          #debug
          echo "$pr_id __ $depl_id"
          echo "$body"

          gh variable set SALTO_DEPL_ID --body "$body"

        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GWR_GH_TOKEN }}

